Add -std=c++14 when not MSVC
To address:

[14/24] Performing build step for 'clang'
FAILED: clang-prefix/src/clang-stamp/clang-build
cd /work/build/clang-prefix/src/clang-build && /usr/local/bin/ninja -v && /usr/bin/cmake -E touch /work/build/clang-prefix/src/clang-stamp/clang-build
[1/1056] /opt/rh/devtoolset-4/root/usr/bin/g++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iutils/TableGen -I/work/build/cfe-10.0.0/utils/TableGen -I/work/build/cfe-10.0.0/include -Iinclude -I/work/build/llvm/include -w -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wdelete-non-virtual-dtor -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -pedantic -Wno-long-long -O3 -DNDEBUG    -fno-exceptions -fno-rtti -MD -MT utils/TableGen/CMakeFiles/clang-tblgen.dir/ClangAttrEmitter.cpp.o -MF utils/TableGen/CMakeFiles/clang-tblgen.dir/ClangAttrEmitter.cpp.o.d -o utils/TableGen/CMakeFiles/clang-tblgen.dir/ClangAttrEmitter.cpp.o -c /work/build/cfe-10.0.0/utils/TableGen/ClangAttrEmitter.cpp
FAILED: utils/TableGen/CMakeFiles/clang-tblgen.dir/ClangAttrEmitter.cpp.o
/opt/rh/devtoolset-4/root/usr/bin/g++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iutils/TableGen -I/work/build/cfe-10.0.0/utils/TableGen -I/work/build/cfe-10.0.0/include -Iinclude -I/work/build/llvm/include -w -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wdelete-non-virtual-dtor -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -pedantic -Wno-long-long -O3 -DNDEBUG    -fno-exceptions -fno-rtti -MD -MT utils/TableGen/CMakeFiles/clang-tblgen.dir/ClangAttrEmitter.cpp.o -MF utils/TableGen/CMakeFiles/clang-tblgen.dir/ClangAttrEmitter.cpp.o.d -o utils/TableGen/CMakeFiles/clang-tblgen.dir/ClangAttrEmitter.cpp.o -c /work/build/cfe-10.0.0/utils/TableGen/ClangAttrEmitter.cpp
In file included from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/type_traits:35:0,
                 from /work/build/llvm/include/llvm/Support/SwapByteOrder.h:20,
                 from /work/build/llvm/include/llvm/ADT/Hashing.h:49,
                 from /work/build/llvm/include/llvm/ADT/ArrayRef.h:12,
                 from /work/build/llvm/include/llvm/TableGen/Record.h:17,
                 from /work/build/cfe-10.0.0/utils/TableGen/ASTTableGen.h:12,
                 from /work/build/cfe-10.0.0/utils/TableGen/ClangAttrEmitter.cpp:14:
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.